[tool.poetry]
name = "806e6eaa2b96e5"
version = "0.1.0"
description = ""
authors = ["hyamakaw"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
